server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
      - id: student
        uri: lb://student-service
        predicates:
        - Path=/student/**
      - id: subject
        uri: lb://subject-service
        predicates:
        - Path=/subject/**


